apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      tolerations:
      - key: app
        operator: Equal
        value: release2
        effect: NoExecute  
      containers:
      - name: my-app-container
        image: omarmfathy219/flask-app:v4
        command:
        - "sh"
        - "-c"
        - sleep 3600
        ports:
        - containerPort: 8000 
