apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-service-account
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::687924512625:role/my-role
imagePullSecrets:
  - name: my-secret
  
